### ISSUE TITLE
Very unoptimized

### ISSUE THREAD

**Issue by terminal-cs** [ascpixi/is-odd#1]
This could be lots simpler:

```js
function isOdd(n) {
return n % 2 == 0;
}
```

**Comment by ascpixi** [comment]
I would like to express my appreciation for your suggestion and the time you have invested in creating it. However, I regret to inform you that the proposed implementation conflicts with the WET technique utilized in our codebase.

Currently, the existing implementation is optimized for JavaScript environments that run on ISAs that may lack an Arithmetic Logic Unit (ALU) or do not incorporate a built-in modulo instruction. In the absence of such a unit, these architectures are compelled to resort to non-standard undefined behavior methods to attain the desired results. Consequently, relying on the modulo operator to achieve this is not a viable option.

To optimize the codebase's performance and compatibility, our team utilizes the WET technique. This approach prioritizes writing code that works effectively and reliably across a range of environments, rather than taking shortcuts that could potentially compromise compatibility or performance.

We appreciate your input and welcome further suggestions or feedback that comply with the established standards and guidelines. Thank you for your understanding.

**Comment by d-002** [comment]
I would like to add that your suggested solution lacks indentation, which makes for a poorer understanding.
